
final _path = "assets/images/";
final _extension = ".svg";

final weatherIcons = {
  "11" : _getImagePath("Sun"),
  "11n" : _getImagePath("Moon"),
  "12" : _getImagePath("Cloud-Sun"),
  "12n" : _getImagePath("Cloud-Moon"),
  "13" : _getImagePath("Cloud-Sun"),
  "13n" : _getImagePath("Cloud-Moon"),
  "14" : _getImagePath("Cloud-Sun"),
  "14n" : _getImagePath("Cloud-Moon"),
  "15" : _getImagePath("Cloud"),
  "15n" : _getImagePath("Cloud"),
  "16" : _getImagePath("Cloud"),
  "16n" : _getImagePath("Cloud"),
  "17" : _getImagePath("Cloud-Fog-Sun"),
  "17n" : _getImagePath("Cloud-Fog-Moon"),
  "23" : _getImagePath("Cloud-Fog-Sun-Alt"),
  "23n" : _getImagePath("Cloud-Fog-Moon-Alt"),
  "24" : _getImagePath("Cloud-Drizzlz-Sun"),
  "24n" : _getImagePath("Cloud-Drizzle-Moon"),
  "25" : _getImagePath("Cloud-Rain-Sun"),
  "25n" : _getImagePath("Cloud-Rain-Moon"),
  "26" : _getImagePath("Cloud-Rain"),
  "26n" : _getImagePath("Cloud-Rain"),
  "27" : _getImagePath("Cloud-Rain-Sun"),
  "27n" : _getImagePath("Cloud-Rain-Moon"),
  "33" : _getImagePath("Cloud-Snown-Sun-Alt"),
  "33n" : _getImagePath("Cloud-Snow-Moon-Alt"),
  "34" : _getImagePath("Cloud-Snown-Sun"),
  "34n" : _getImagePath("Cloud-Snow-Moon"),
  "35" : _getImagePath("Cloud-Snown-Alt"),
  "35n" : _getImagePath("Cloud-Snow-Alt"),
  "36" : _getImagePath("Cloud-Snown"),
  "36n" : _getImagePath("Cloud-Snow"),
  "43" : _getImagePath("Cloud-Drizzlz-Sun-Alt"),
  "43n" : _getImagePath("Cloud-Drizzle-Moon-Alt"),
  "44" : _getImagePath("Cloud-Drizzlz-Sun-Alt"),
  "44n" : _getImagePath("Cloud-Drizzle-Moon-Alt"),
  "45" : _getImagePath("Cloud-Drizzlz-Alt"),
  "45n" : _getImagePath("Cloud-Drizzle-Alt"),
  "46" : _getImagePath("Cloud-Drizzlz"),
  "46n" : _getImagePath("Cloud-Drizzle"),
  "51" : _getImagePath("Cloud-Lightning-Sun"),
  "51n" : _getImagePath("Cloud-Lightning-Moon"),
  "52" : _getImagePath("Cloud-Lightning-Sun"),
  "52n" : _getImagePath("Cloud-Lightning-Moon"),
  "53" : _getImagePath("Cloud-Lightning"),
  "53n" : _getImagePath("Cloud-Lightning"),
  "54" : _getImagePath("Cloud-Lightning"),
  "54n" : _getImagePath("Cloud-Lightning"),
  "61" : _getImagePath("Cloud-Lightning-Sun"),
  "61n" : _getImagePath("Cloud-Lightning-Moon"),
  "62" : _getImagePath("Cloud-Lightning-Sun"),
  "62n" : _getImagePath("Cloud-Lightning-Moon"),
  "63" : _getImagePath("Cloud-Lightning"),
  "63n" : _getImagePath("Cloud-Lightning"),
  "64" : _getImagePath("Cloud-Lightning"),
  "64n" : _getImagePath("Cloud-Lightning"),
  "71" : _getImagePath("Cloud-Snown-Alt"),
  "71n" : _getImagePath("Cloud-Snow-Alt"),
  "72" : _getImagePath("Cloud-Snown-Alt"),
  "72n" : _getImagePath("Cloud-Snow-Alt"),
  "73" : _getImagePath("Cloud-Snown-Alt"),
  "73n" : _getImagePath("Cloud-Snow-Alt"),
  "74" : _getImagePath("Cloud-Snown-Alt"),
  "74n" : _getImagePath("Cloud-Snow-Alt"),
  "81" : _getImagePath("Cloud-Fog"),
  "81n" : _getImagePath("Cloud-Fog"),
  "82" : _getImagePath("Cloud-Fog"),
  "82n" : _getImagePath("Cloud-Fog"),
  "83" : _getImagePath("Cloud-Fog-Sun-Alt"),
  "83n" : _getImagePath("Cloud-Fog-Moon-Alt"),
};

String _getImagePath(String imageName) => "$_path$imageName$_extension";